select	CONVERT(DECIMAL(13,3),RAND(CHECKSUM(NEWID())) + ABS(CHECKSUM(NEWID())) % POWER(10, ABS(CHECKSUM(NEWID())%10)))
	,	CONVERT(float,RAND(CHECKSUM(NEWID())) + ABS(CHECKSUM(NEWID())) % POWER(10, ABS(CHECKSUM(NEWID())%8)))
	,	CONVERT(real,RAND(CHECKSUM(NEWID())) + ABS(CHECKSUM(NEWID())) % POWER(10, ABS(CHECKSUM(NEWID())%8)))
from	sys.columns

